/* X Localtime - city list with their IANA timezones */
window.LT_CITIES = [
  { fa: 'تهران', en: 'Tehran', tz: 'Asia/Tehran' },
  { fa: 'مشهد', en: 'Mashhad', tz: 'Asia/Tehran' },
  { fa: 'اصفهان', en: 'Isfahan', tz: 'Asia/Tehran' },
  { fa: 'شیراز', en: 'Shiraz', tz: 'Asia/Tehran' },
  { fa: 'تبریز', en: 'Tabriz', tz: 'Asia/Tehran' },

  { fa: 'تورنتو', en: 'Toronto', tz: 'America/Toronto' },
  { fa: 'مونترال', en: 'Montreal', tz: 'America/Toronto' },
  { fa: 'اتاوا', en: 'Ottawa', tz: 'America/Toronto' },
  { fa: 'ونکوور', en: 'Vancouver', tz: 'America/Vancouver' },
  { fa: 'کلگری', en: 'Calgary', tz: 'America/Edmonton' },
  { fa: 'ادمونتون', en: 'Edmonton', tz: 'America/Edmonton' },
  { fa: 'وینیپگ', en: 'Winnipeg', tz: 'America/Winnipeg' },
  { fa: 'هلیفکس', en: 'Halifax', tz: 'America/Halifax' },

  { fa: 'نیویورک', en: 'New York', tz: 'America/New_York' },
  { fa: 'واشنگتن', en: 'Washington DC', tz: 'America/New_York' },
  { fa: 'شیکاگو', en: 'Chicago', tz: 'America/Chicago' },
  { fa: 'هیوستون', en: 'Houston', tz: 'America/Chicago' },
  { fa: 'دنور', en: 'Denver', tz: 'America/Denver' },
  { fa: 'فینیکس', en: 'Phoenix', tz: 'America/Phoenix' },
  { fa: 'لس‌آنجلس', en: 'Los Angeles', tz: 'America/Los_Angeles' },
  { fa: 'سان‌فرانسیسکو', en: 'San Francisco', tz: 'America/Los_Angeles' },
  { fa: 'سیاتل', en: 'Seattle', tz: 'America/Los_Angeles' },
  { fa: 'مکزیکوسیتی', en: 'Mexico City', tz: 'America/Mexico_City' },
  { fa: 'سائوپائولو', en: 'Sao Paulo', tz: 'America/Sao_Paulo' },
  { fa: 'بوئنوس آیرس', en: 'Buenos Aires', tz: 'America/Argentina/Buenos_Aires' },

  { fa: 'لندن', en: 'London', tz: 'Europe/London' },
  { fa: 'دوبلین', en: 'Dublin', tz: 'Europe/Dublin' },
  { fa: 'پاریس', en: 'Paris', tz: 'Europe/Paris' },
  { fa: 'برلین', en: 'Berlin', tz: 'Europe/Berlin' },
  { fa: 'فرانکفورت', en: 'Frankfurt', tz: 'Europe/Berlin' },
  { fa: 'آمستردام', en: 'Amsterdam', tz: 'Europe/Amsterdam' },
  { fa: 'بروکسل', en: 'Brussels', tz: 'Europe/Brussels' },
  { fa: 'مادرید', en: 'Madrid', tz: 'Europe/Madrid' },
  { fa: 'بارسلونا', en: 'Barcelona', tz: 'Europe/Madrid' },
  { fa: 'لیسبون', en: 'Lisbon', tz: 'Europe/Lisbon' },
  { fa: 'رم', en: 'Rome', tz: 'Europe/Rome' },
  { fa: 'میلان', en: 'Milan', tz: 'Europe/Rome' },
  { fa: 'زوریخ', en: 'Zurich', tz: 'Europe/Zurich' },
  { fa: 'وین', en: 'Vienna', tz: 'Europe/Vienna' },
  { fa: 'استکهلم', en: 'Stockholm', tz: 'Europe/Stockholm' },
  { fa: 'اسلو', en: 'Oslo', tz: 'Europe/Oslo' },
  { fa: 'کپنهاگ', en: 'Copenhagen', tz: 'Europe/Copenhagen' },
  { fa: 'هلسینکی', en: 'Helsinki', tz: 'Europe/Helsinki' },
  { fa: 'ورشو', en: 'Warsaw', tz: 'Europe/Warsaw' },
  { fa: 'پراگ', en: 'Prague', tz: 'Europe/Prague' },
  { fa: 'بوداپست', en: 'Budapest', tz: 'Europe/Budapest' },
  { fa: 'آتن', en: 'Athens', tz: 'Europe/Athens' },
  { fa: 'استانبول', en: 'Istanbul', tz: 'Europe/Istanbul' },
  { fa: 'مسکو', en: 'Moscow', tz: 'Europe/Moscow' },
  { fa: 'کی‌یف', en: 'Kyiv', tz: 'Europe/Kyiv' },

  { fa: 'دبی', en: 'Dubai', tz: 'Asia/Dubai' },
  { fa: 'ابوظبی', en: 'Abu Dhabi', tz: 'Asia/Dubai' },
  { fa: 'دوحه', en: 'Doha', tz: 'Asia/Qatar' },
  { fa: 'ریاض', en: 'Riyadh', tz: 'Asia/Riyadh' },
  { fa: 'کویت', en: 'Kuwait', tz: 'Asia/Kuwait' },
  { fa: 'بغداد', en: 'Baghdad', tz: 'Asia/Baghdad' },
  { fa: 'اربیل', en: 'Erbil', tz: 'Asia/Baghdad' },
  { fa: 'بیروت', en: 'Beirut', tz: 'Asia/Beirut' },
  { fa: 'دمشق', en: 'Damascus', tz: 'Asia/Damascus' },
  { fa: 'قاهره', en: 'Cairo', tz: 'Africa/Cairo' },
  { fa: 'باکو', en: 'Baku', tz: 'Asia/Baku' },
  { fa: 'ایروان', en: 'Yerevan', tz: 'Asia/Yerevan' },
  { fa: 'تفلیس', en: 'Tbilisi', tz: 'Asia/Tbilisi' },
  { fa: 'کابل', en: 'Kabul', tz: 'Asia/Kabul' },
  { fa: 'کراچی', en: 'Karachi', tz: 'Asia/Karachi' },
  { fa: 'دهلی نو', en: 'New Delhi', tz: 'Asia/Kolkata' },
  { fa: 'بمبئی', en: 'Mumbai', tz: 'Asia/Kolkata' },
  { fa: 'داکا', en: 'Dhaka', tz: 'Asia/Dhaka' },
  { fa: 'بانکوک', en: 'Bangkok', tz: 'Asia/Bangkok' },
  { fa: 'سنگاپور', en: 'Singapore', tz: 'Asia/Singapore' },
  { fa: 'کوالالامپور', en: 'Kuala Lumpur', tz: 'Asia/Kuala_Lumpur' },
  { fa: 'جاکارتا', en: 'Jakarta', tz: 'Asia/Jakarta' },
  { fa: 'هنگ‌کنگ', en: 'Hong Kong', tz: 'Asia/Hong_Kong' },
  { fa: 'پکن', en: 'Beijing', tz: 'Asia/Shanghai' },
  { fa: 'شانگهای', en: 'Shanghai', tz: 'Asia/Shanghai' },
  { fa: 'توکیو', en: 'Tokyo', tz: 'Asia/Tokyo' },
  { fa: 'سئول', en: 'Seoul', tz: 'Asia/Seoul' },
  { fa: 'تاشکند', en: 'Tashkent', tz: 'Asia/Tashkent' },
  { fa: 'آلماتی', en: 'Almaty', tz: 'Asia/Almaty' },

  { fa: 'سیدنی', en: 'Sydney', tz: 'Australia/Sydney' },
  { fa: 'ملبورن', en: 'Melbourne', tz: 'Australia/Melbourne' },
  { fa: 'بریزبن', en: 'Brisbane', tz: 'Australia/Brisbane' },
  { fa: 'پرت', en: 'Perth', tz: 'Australia/Perth' },
  { fa: 'اوکلند', en: 'Auckland', tz: 'Pacific/Auckland' },

  { fa: 'ژوهانسبورگ', en: 'Johannesburg', tz: 'Africa/Johannesburg' },
  { fa: 'نایروبی', en: 'Nairobi', tz: 'Africa/Nairobi' },
  { fa: 'لاگوس', en: 'Lagos', tz: 'Africa/Lagos' },
  { fa: 'کازابلانکا', en: 'Casablanca', tz: 'Africa/Casablanca' },

  { fa: 'زمان جهانی (UTC)', en: 'UTC', tz: 'UTC' }
];
